codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "85...100"
  
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 1%

parsers:
  javascript:
    enable_partials: yes

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/test/**"
  - "**/tests/**"
  - "**/examples/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false